spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studentDB?createDatabaseIfNotExist=true
    username: root
    password: virtusa@1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create